version: '3.8'

services:
  gemini-bot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gemini-bot-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - HEALTH_CHECK_PORT=3001
    env_file:
      - .env
    ports:
      - '3001:3001' # Health check endpoint
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - bot-dev-network
    command: npm run dev

networks:
  bot-dev-network:
    driver: bridge
